# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lab3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lab3

  target 'Lab3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lab3UITests' do
    # Pods for testing
  end

end
